# resources.properties ???? ?? yml? ??
server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/spring_board
    username: root
    password: 1234
  jpa:
    database: mysql
    # mysql???? ????? ?? ???? InnoDB? ?????? ??
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # jpa ??. ddl? ???? ?????? ??
    generate-ddl: true
    hibernate:

      # create ??? ?? table? drop ? ??
      # update ??? ????? alter? ??
      # ????? validate ???? ??? ?? ??? ???
      ddl-auto: update
    # show_sql : true? jpa? ???? query? ???? ??? console?? ????? ?? ??
    show_sql: true
logging:
  level:
# log.error로그 이상만 출력 : Trace<debug<info<error
# 실무에서는 일반적으로 info로 설정, info는 굳이 설정안해도 default가 info다.
    root: info