# resources.properties ???? ?? yml? ??
server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/spring_board
    username: root
    password: 1234
  jpa:
    database: mysql
    # mysql???? ????? ?? ???? InnoDB? ?????? ??
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # jpa ??. ddl? ???? ?????? ??
    generate-ddl: true
    hibernate:

      # create ??? ?? table? drop ? ??
      # update ??? ????? alter? ??
      # ????? validate ???? ??? ?? ??? ???
      ddl-auto: create
    # show_sql : true? jpa? ???? query? ???? ??? console?? ????? ?? ??
    show_sql: true